<?php

include_once 'flying_presi.features.inc';

/**
 * Implements hook_theme().
 */
function flying_presi_theme() {
  return array(
    'flying_presentation' => array(
      'arguments' => array('element' => NULL),
      'file' => 'flying_presi.theme.inc',
    ),
    'flying_presentation_data' => array(
      'arguments' => array('element' => NULL),
      'file' => 'flying_presi.theme.inc',
    ),
    'list' => array(
      'arguments' => array('element' => NULL),
      'file' => 'flying_presi.theme.inc',
    ),
  );
}

function flying_presi_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'project') {
    if ($op == 'view') {

      $project_data = theme('flying_presentation_data', $node->nid);
      $flying_presentation = theme('flying_presentation', $project_data);

      $node->content['body']['#value'] .= $flying_presentation;
    }
  }
}